from __future__ import annotations

from datetime import date
from typing import List, Optional, Protocol

from Model.entities import Booking, Campaign, ContactInfo, Location, User


class UserRepository(Protocol):
    def add(self, user: User) -> User: ...

    def get(self, user_id: int) -> Optional[User]: ...

    def list(self) -> List[User]: ...


class ContactRepository(Protocol):
    def add(self, contact: ContactInfo) -> ContactInfo: ...

    def list_by_user(self, user_id: int) -> List[ContactInfo]: ...


class LocationRepository(Protocol):
    def add(self, location: Location) -> Location: ...

    def get(self, location_id: int) -> Optional[Location]: ...

    def list(self) -> List[Location]: ...


class CampaignRepository(Protocol):
    def add(self, campaign: Campaign) -> Campaign: ...

    def get(self, campaign_id: int) -> Optional[Campaign]: ...

    def list(self) -> List[Campaign]: ...


class BookingRepository(Protocol):
    def add(self, booking: Booking) -> Booking: ...

    def list(self) -> List[Booking]: ...

    def list_by_location_date(self, location_id: int, event_date: date) -> List[Booking]: ...
