name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  test-pyramid:
    name: test-pyramid
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Unit-Tests
        run: python -m unittest discover -s tests/unit -p "test_*.py" -v

      - name: Integration-Tests
        run: python -m unittest discover -s tests/integration -p "test_*.py" -v

      - name: E2E-Tests
        run: python -m unittest discover -s tests/e2e -p "test_*.py" -v
